version: 2

jobs:
  build:
    # working_directory: ~/demo_project

    docker:
      - image: walberla/buildenv-ubuntu-gcc:4.8
        environment:

    steps:
      - checkout

      - run:
          name: Compile tests
          command: make test
