version: 2
jobs:
  dependencies:
    pre:
      - sudo apt-get update; sudo apt-get install build-essential
  build:
    steps:
      - checkout
      - run:
          name: Tests
          command: make test
