version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Tooling
          command: sudo apt-get install gcc make -y
      - run:
          name: Tests
          command: make test
