version: 2
dependencies:
  pre:
    - sudo apt-get update; sudo apt-get install build-essential
jobs:
  build:
    steps:
      - checkout
      - run:
          name: Tests
          command: make test
