version: 2

jobs:
  build:
    # working_directory: ~/demo_project

    docker:
      - image: comodal/alpine-gcc-make:latest
        environment:

    steps:
      - checkout

      - run:
          name: Compile tests
          command: make test
